model:
    name: alexnet
    experiment_name: alexnet_baseline
    num_classes: 45
    pretrained: True

train:
    epochs: 5
    batch_size: 32
    lr: 0.001
    save_dir: experiments/alexnet_baseline/
    param_group: classifier

data:
    # instead of width and height. smaller side will be reduced
    img_size: 224
    