model:
    name: resnet34
    experiment_name: resnet34_baseline
    num_classes: 45
    pretrained: True

train:
    epochs: 5
    batch_size: 16
    lr: 0.0001
    weight_decay: 0.0001
    save_dir: experiments/resnet34_baseline/
    param_group: fc

data:
    img_size: 224
    